version: '3.4'

services:
  django:
    build: .
    volumes:
    - .:/home/django
    - static_volume:/media/www
    environment:
      - PRODUCTION=1
    env_file:
      - /home/hyperion/secret/email_ovh.env
    expose:
      - 6023
    networks:
      - upstream_net
      - cache_net
    secrets:
      - email_password
    depends_on:
      - memcache
    restart: always

  memcache:
    container_name: memcache
    image: memcached:1.6-alpine
    ports:
      - 11211
    networks:
      - cache_net
    entrypoint:
      - memcached
      - -m 64
    restart: always

  nginx:
    container_name: nginx_static
    build: ./nginx
    volumes:
    - static_volume:/media/www
    ports:
      - 6023:80
    networks:
      - upstream_net
    depends_on:
      - django
    restart: always

volumes:
  static_volume:

networks:
  cache_net:
    driver: bridge
  upstream_net:
    driver: bridge
  default:
    external:
      name: host
      
secrets:
  email_password:
    file: /home/hyperion/secret/email_ovh.env
